# Generated by Django 2.1.5 on 2020-02-14 01:48
from django.db import migrations, models
from rango.models import Category

class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20200214_0034'),
    ]

    def gen_slug(apps, schema_editor):
        for row in Category.objects.all():
            row.slug = slugify(row.name)
            row.save()

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
            preserve_default=True,
        ),
        migrations.RunPython(gen_slug),

        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
